project:
  name: Cart
  debug: true
  environment: development

server:
  host: 0.0.0.0
  port: 8082

productService:
  apiuri: "http://route256.pavl.uk:8080"
  token: testtoken
  maxRetries: 3

lomsService:
  host: "0.0.0.0"
  port: "50051"

jaeger:
  uri: "localhost:4318"

metrics:
  uri: "0.0.0.0:2112"

cache:
  capacity: 100

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  ttl: 600

graylog:
  uri: "0.0.0.0:12201"