// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID      int64
	OrderID *int64
	Sku     int32
	Count   int16
}

type Order struct {
	ID        int64
	UserID    int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Stock struct {
	Sku        int32
	TotalCount int64
	Reserved   int64
}
