// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package sqlc

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status)
VALUES ($1, $2)
RETURNING id, user_id, status, created_at
`

type CreateOrderParams struct {
	UserID int64
	Status string
}

func (q *Queries) CreateOrder(ctx context.Context, arg *CreateOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO items (order_id, sku, count)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateOrderItemParams struct {
	OrderID *int64
	Sku     int32
	Count   int16
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg *CreateOrderItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrderItem, arg.OrderID, arg.Sku, arg.Count)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (*Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, sku, count
FROM items
WHERE order_id = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID *int64) ([]*Item, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Sku,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE orders
SET status = $2
WHERE id = $1
`

type SetOrderStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg *SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.ID, arg.Status)
	return err
}
